-- Problem 12
--[[
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
    The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55.
    28 is the first triangle number to have over five divisors.
    What is the value of the first triangle number to have over five hundred divisors?
]]

-- TODO: Improve with /number of divisors/ algo


local prod = 1


function FindAllDivisors(num)
    local divisors = {}
    local temp = num
    for i = 1, num do
        if num%i == 0 then
            temp = num/i
            if i>temp then break end
            table.insert(divisors, i)
            if num/i ~= i then 
                table.insert(divisors, num/i)
            end
        end
        
    end
    return divisors
end



local num = 1
local next = 2
while (#FindAllDivisors(num)<500) do
    num  = num + next
    next = next +1
end


print(num)
